[phases.setup]
nixPkgs = ["ruby_4_0", "nodejs_20", "postgresql"]

[phases.install]
cmds = ["bundle install"]

[phases.build]
cmds = ["bundle exec bootsnap precompile --gemfile", "SECRET_KEY_BASE_DUMMY=1 bundle exec rails assets:precompile"]

[phases.release]
cmds = ["bundle exec rails db:migrate && bundle exec rails db:seed"]

[start]
cmd = "bundle exec puma -C config/puma.rb"