default: &default
  adapter: postgresql
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("USERNAME", "username") %>
  password: <%= ENV.fetch("PASSWORD", "password") %>
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: yourapp_development

test:
  <<: *default
  database: yourapp_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>